version: '3.8'

services:
  web:
    build: .
    container_name: sena_flask_app
    expose:
      - "5001"
    volumes:
      - .:/app
      # Evitamos sobrescribir los directorios de entorno virtual y caché generados localmente
      - /app/.venv
      - /app/__pycache__
    env_file:
      - .env
   
    restart: unless-stopped
    # command: ["python", "run.py"] # Ya está definido en el Dockerfile, pero puede sobreescribirse aquí si es necesario


